  - name: Install all sql required dependencies
    apt: name={{ item }} state=present
    with_items:
    - mysql-server
    - mysql-client

  - name: Start database service
    service:
      name: mysql
      state: started
      enabled: yes

  - name: Update mysql root password for all root account
    mysql_user:
      name: root
      host: '{{ item }}'
      password: '{{ db_root_password }}'
      login_user: root
      login_password: '{{ db_root_password }}'
      check_implicit_admin: yes
      priv: '*.*:ALL,GRANT'
    with_items:
    - '{{ ansible_host }}'
    - 127.0.0.1
    - localhost

  - name: Create Application Database
    mysql_db:
      name: '{{ db_name }}'
      state: present
      login_user: root
      login_password: '{{ db_root_password }}'

  - name: Create database user
    mysql_user:
      name: '{{ db_user }}'
      password: '{{ db_password }}'
      priv: '*.*:ALL'
      state: present
      host: '%'
      login_user: root
      login_password: '{{ db_root_password }}'