- name: Deploy a webapp
  hosts: db_and_webapp
  become : true
  tasks:
  - name: Install all python required dependencies
    apt: name={{ item }} state=present
    with_items:
    - python3
    - python3-setuptools
    - python3-dev
    - build-essential
    - python3-pip
    - python3-mysqldb

  - include: tasks/deploy_db.yml
  - include: tasks/deploy_web.yml

